# ManagedClusterSetBinding is required for the Placement API to schedule
# clusters from the default ManagedClusterSet in this namespace.
{{- if .Values.clusterGroup.managedClusterGroups }}
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterSet: default
{{- end }}
